services:
  app-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - app-back
    # networks:
    #   - backend
  app-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    # networks:
    #   - backend

  db:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - data_mongo:/data/db
    # networks:
    #   - backend

volumes:
  data_mongo:

# networks:
#   backend:
