services:
  app-front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - app-back
    networks:
      - backend
      - static
  app-back:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - data_mongo:/data/db
    networks:
      - backend

  assets:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./assets:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - static

volumes:
  data_mongo:
  data_build:

networks:
  backend:
  static:
