name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build_and_push:
    name: Build and Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker image
        run: |
          docker build -f ./frontend/Dockerfile -t username42013/tpdocker-frontname:latest ./frontend
          docker push username42013/tpdocker-frontend:latest

      - name: Build and Push Backend Docker image
        run: |
          docker build -f ./backend/Dockerfile -t username42013/tpdocker-backend:latest ./backend
          docker push username42013/tpdocker-backend:latest
